project_id = "tsduibmoqntxqdaswbef"

[functions.cashfree-webhook]
verify_jwt = false

[functions.affiliate-click]
verify_jwt = false

[functions.affiliate-conversion]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false

[functions.resend-webhook]
verify_jwt = false

[functions.send-contact-message]
verify_jwt = false