project_id = "tsduibmoqntxqdaswbef"

[functions.cashfree-webhook]
verify_jwt = false

[functions.affiliate-click]
verify_jwt = false

[functions.affiliate-conversion]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false

[functions.resend-webhook]
verify_jwt = false

[functions.send-contact-message]
verify_jwt = false

[functions.affiliate-merchant-webhook]
verify_jwt = false

[functions.affiliate-utm-return]
verify_jwt = false

[functions.affiliate-weekly-summary]
verify_jwt = false

[functions.visitor-alert]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.andaman-news-agent]
verify_jwt = false